[package]
name = "cidr_lookup"
version = "0.1.0"
authors = ["Amos Paul <amos@cloudflare.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
